import { Country } from "module/country/country.model";
import { logger } from "../logger/logger";

const countries = [
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    currency: "BDT",
    currencySymbol: "৳",
    timezone: "Asia/Dhaka",
    messageCreditPrice: 16.6,
    callCreditPrice: 16.6,
    smsProviders: ["twilio"],
    isActive: true,
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    currency: "INR",
    currencySymbol: "₹",
    timezone: "Asia/Kolkata",
    messageCreditPrice: 12.8,
    callCreditPrice: 12.8,
    smsProviders: ["twilio"],
    isActive: true,
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    currency: "KES",
    currencySymbol: "KSh",
    timezone: "Africa/Nairobi",
    messageCreditPrice: 17.2,
    callCreditPrice: 17.2,
    smsProviders: ["africas_talking"],
    isActive: true,
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    currency: "UGX",
    currencySymbol: "USh",
    timezone: "Africa/Kampala",
    messageCreditPrice: 500,
    callCreditPrice: 500,
    smsProviders: ["africas_talking"],
    isActive: true,
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    currency: "NGN",
    currencySymbol: "₦",
    timezone: "Africa/Lagos",
    messageCreditPrice: 183.0,
    callCreditPrice: 183.0,
    smsProviders: ["africas_talking"],
    isActive: true,
  },
  {
    name: "Tanzania",
    code: "TZ",
    phoneCode: "+255",
    currency: "TZS",
    currencySymbol: "TSh",
    timezone: "Africa/Dar_es_Salaam",
    messageCreditPrice: 355.4,
    callCreditPrice: 355.4,
    smsProviders: ["africas_talking"],
    isActive: true,
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    currency: "GHS",
    currencySymbol: "GH₵",
    timezone: "Africa/Accra",
    messageCreditPrice: 1.6,
    callCreditPrice: 1.6,
    smsProviders: ["africas_talking"],
    isActive: true,
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneCode: "+92",
    currency: "PKR",
    currencySymbol: "Rs",
    timezone: "Asia/Karachi",
    messageCreditPrice: 37.3,
    callCreditPrice: 37.3,
    smsProviders: ["twilio"],
    isActive: true,
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    currency: "ZAR",
    currencySymbol: "R",
    timezone: "Africa/Johannesburg",
    messageCreditPrice: 2.2,
    callCreditPrice: 2.2,
    smsProviders: ["twilio"],
    isActive: true,
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    currency: "EGP",
    currencySymbol: "E£",
    timezone: "Africa/Cairo",
    messageCreditPrice: 6.7,
    callCreditPrice: 6.7,
    smsProviders: ["twilio"],
    isActive: true,
  },
];

const seedCountries = async () => {
  for (const c of countries) {
    await Country.findOneAndUpdate({ code: c.code }, c, { upsert: true, new: true });
  }
  logger.info(`[seed] Seeded and updated ${countries.length} countries with 500 UGX equivalent prices`);
};

export default seedCountries;
